<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Annium.XRest.Core/Annium.XRest.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Extensions.Arguments" />
    <PackageReference Include="Annium.Net.Http" />
    <PackageReference Include="Scriban" />
  </ItemGroup>
</Project>
