<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Annium.XRest.Sources.Shared/Annium.XRest.Sources.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" />
  </ItemGroup>
</Project>
