version: "3.6"
services:
  api:
    build:
      context: ../src
      dockerfile: Backuper.Api/Dockerfile
    image: backuper
    container_name: backuper_api
    restart: always
    ports:
      - "9991:5000"
    volumes:
      - "../run/configuration:/app/configuration"
      - "../run/data:/app/data"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  default:
    external:
      name: backuper_net
