<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>XRest.Core</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XRest.Core</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>preview</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Primitives" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Reflection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime.Loader" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Abstractions" Version="0.1.0" />
        <PackageReference Include="Annium.Serialization.Json" Version="0.1.0" />
        <PackageReference Include="Scriban" Version="3.5.0" />
    </ItemGroup>
</Project>