<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Net.Types.Serialization.Json" />
    <PackageReference Include="Annium.Serialization.Json" />
  </ItemGroup>
</Project>
