<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <PackageId>Backuper.Api</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Backuper Api</Description>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Backuper.Connection.PostgreSQL/Backuper.Connection.PostgreSQL.csproj" />
        <ProjectReference Include="../Backuper.Notification.Slack/Backuper.Notification.Slack.csproj" />
        <ProjectReference Include="../Backuper.Storage/Backuper.Storage.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.AspNetCore.Extensions" Version="0.1.0" />
        <PackageReference Include="Annium.Configuration.Yaml" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Mapper" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Mediator" Version="0.1.0" />
        <PackageReference Include="Annium.Diagnostics.Debug" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Jobs" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Microsoft" Version="0.1.0" />
        <PackageReference Include="Annium.NodaTime.Serialization.Json" Version="0.1.0" />
        <PackageReference Include="NodaTime" Version="3.0.0" />
    </ItemGroup>
</Project>