<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Backuper.Connection.Abstract/Backuper.Connection.Abstract.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
