<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xmg.Configuration.linq2db</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xmg.Configuration.linq2db</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>9.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xmg.Configuration.Abstractions/Xmg.Configuration.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.Runtime.Loader" Version="0.1.0" />
        <PackageReference Include="Annium.linq2db.Extensions" Version="0.1.0" />
    </ItemGroup>
</Project>