<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Xmg.Configuration.Abstractions/Xmg.Configuration.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Core.Runtime.Loader" />
    <PackageReference Include="Annium.linq2db.Extensions" />
  </ItemGroup>
</Project>
