<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xdb.Core</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xdb.Core</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium" Version="0.1.0" />
        <PackageReference Include="dbup-mysql" Version="5.0.10" />
        <PackageReference Include="dbup-postgresql" Version="5.0.8" />
        <PackageReference Include="dbup-sqlite" Version="5.0.8" />
        <PackageReference Include="dbup-sqlserver" Version="5.0.8" />
    </ItemGroup>
</Project>