<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../XRest.Sources.Shared/XRest.Sources.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Data.Operations.Serialization.Json" />
    <PackageReference Include="Annium.NodaTime.Serialization.Json" />
    <PackageReference Include="NSwag.AspNetCore" />
  </ItemGroup>
</Project>
