<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>MessageBus.Sink</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>MessageBus.Sink</Description>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>10.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Configuration.CommandLine" Version="0.1.0" />
        <PackageReference Include="Annium.Configuration.Yaml" Version="0.1.0" />
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Mapper" Version="0.1.0" />
        <PackageReference Include="Annium.Infrastructure.MessageBus.Node" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="Annium.Serialization.Json" Version="0.1.0" />
    </ItemGroup>
</Project>