<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xws</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xws</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xws</ToolCommandName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium" Version="0.1.0" />
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Reflection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime.Loader" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Infrastructure.WebSockets.Server" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="Annium.Serialization.Json" Version="0.1.0" />
        <PackageReference Include="Scriban" Version="5.5.2" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
</Project>