<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xmg.Migration.Abstractions</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xmg.Migration.Abstractions</Description>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../Xmg.Core/Xmg.Core.csproj" />
    </ItemGroup>
</Project>