<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/sources/XRest.Sources.AspNetCore/XRest.Sources.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.AspNetCore.Extensions" />
    <PackageReference Include="Annium.Configuration.Abstractions" />
    <PackageReference Include="Annium.Infrastructure.Hosting" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Logging.Microsoft" />
  </ItemGroup>
</Project>
