<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>xdomains</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>xdomains</Description>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>10.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xdomains</ToolCommandName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="NodaTime" Version="3.1.0" />
    </ItemGroup>
    <ItemGroup>
        <None Update="zones.txt" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>