<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Debugger</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Debugger</Description>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.linq2db.Extensions" Version="0.1.0" />
    </ItemGroup>
</Project>