<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>XRest.Sources</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XRest.Sources</Description>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>preview</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../XRest.Sources.Api/XRest.Sources.Api.csproj" />
        <ProjectReference Include="../XRest.Sources.Assembly/XRest.Sources.Assembly.csproj" />
    </ItemGroup>
</Project>