<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/clients/Annium.XRest.Clients.Csharp/Annium.XRest.Clients.Csharp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Testing" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
