<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>xrest</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../clients/XRest.Clients.Csharp/XRest.Clients.Csharp.csproj" />
    <ProjectReference Include="../clients/XRest.Clients.TypeScript/XRest.Clients.TypeScript.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="Annium.Logging.Console" />
  </ItemGroup>
</Project>
