<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xa</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xa</Description>
        <Solutions></Solutions>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xa</ToolCommandName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="Glob" Version="1.1.9" />
    </ItemGroup>
</Project>