<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xmg.Migration.FluentMigrator</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xmg.Migration.FluentMigrator</Description>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xmg.Migration.Abstractions/Xmg.Migration.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
</Project>