<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Xmg.Migration.Abstractions/Xmg.Migration.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates/**" />
    <EmbeddedResource Remove="Templates/.*" />
  </ItemGroup>
</Project>
