<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="LibSassHost" />
    <PackageReference Include="LibSassHost.Native.linux-x64" />
    <PackageReference Include="LibSassHost.Native.osx-x64" />
    <PackageReference Include="LibSassHost.Native.win-x64" />
  </ItemGroup>
  <PropertyGroup>
    <NuspecFile>package.nuspec</NuspecFile>
    <NuspecProperties>publishDir=$([MSBuild]::NormalizeDirectory($(MSBuildProjectDirectory)/bin/$(Configuration)))</NuspecProperties>
  </PropertyGroup>
</Project>
