<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>xlog</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="Annium.Extensions.Arguments" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Net.Http" />
    <PackageReference Include="Annium.Serialization.Json" />
    <PackageReference Include="Annium.Serialization.Yaml" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>
</Project>
