<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xmg.Core</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xmg.Core</Description>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Reflection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Primitives" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Abstractions" Version="0.1.0" />
        <PackageReference Include="Scriban" Version="2.1.3" />
    </ItemGroup>
</Project>