<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.Abstractions" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Net.Http" />
  </ItemGroup>
</Project>
