<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Annium.XRest.Clients.Shared/Annium.XRest.Clients.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates/**" />
    <EmbeddedResource Remove="Templates/.*" />
  </ItemGroup>
</Project>
