<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xdb</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xdb</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xdb</ToolCommandName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Configuration.Yaml" Version="0.1.0" />
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
    </ItemGroup>
</Project>