<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>xdb</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Xdb.Core/Xdb.Core.csproj" />
    <ProjectReference Include="../Xdb.PostgreSql/Xdb.PostgreSql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="Annium.Core.Runtime.Loader" />
    <PackageReference Include="Annium.Extensions.Arguments" />
    <PackageReference Include="Annium.linq2db.PostgreSql" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Serialization.Yaml" />
  </ItemGroup>
</Project>
