<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Configuration.CommandLine" />
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="NetMQ" />
  </ItemGroup>
</Project>
