<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>XRest.Clients.Shared</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XRest.Source</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../XRest.Core/XRest.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Net.Http" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Scriban" Version="5.5.2" />
    </ItemGroup>
</Project>