<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Backuper.Shared/Backuper.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Storage.FileSystem" />
    <PackageReference Include="Annium.Storage.S3" />
  </ItemGroup>
</Project>
