<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Backuper.Connection.PostgreSQL/Backuper.Connection.PostgreSQL.csproj" />
    <ProjectReference Include="../Backuper.Notification.Slack/Backuper.Notification.Slack.csproj" />
    <ProjectReference Include="../Backuper.Storage/Backuper.Storage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.AspNetCore.Extensions" />
    <PackageReference Include="Annium.Configuration.Yaml" />
    <PackageReference Include="Annium.Extensions.Jobs" />
    <PackageReference Include="Annium.Logging.Microsoft" />
  </ItemGroup>
</Project>
