<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Annium.Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Backuper.Notification.Abstract/Backuper.Notification.Abstract.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Net.Http" />
  </ItemGroup>
</Project>
