<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Exe</OutputType>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>xmg</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Xmg.Configuration/Xmg.Configuration/Xmg.Configuration.csproj" />
    <ProjectReference Include="../Xmg.Migration/Xmg.Migration/Xmg.Migration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Annium.Core.Entrypoint" />
    <PackageReference Include="Annium.Extensions.Arguments" />
    <PackageReference Include="Annium.Logging.Console" />
    <PackageReference Include="Annium.Serialization.Json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Templates/**" />
    <EmbeddedResource Remove="Templates/.*" />
  </ItemGroup>
</Project>
