<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Xmg</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>Xmg</Description>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <OutputType>Exe</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>latest</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>xmg</ToolCommandName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Xmg.Configuration/Xmg.Configuration/Xmg.Configuration.csproj" />
        <ProjectReference Include="../Xmg.Migration/Xmg.Migration/Xmg.Migration.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Annium.Core.DependencyInjection" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Entrypoint" Version="0.1.0" />
        <PackageReference Include="Annium.Core.Runtime" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Arguments" Version="0.1.0" />
        <PackageReference Include="Annium.Extensions.Primitives" Version="0.1.0" />
        <PackageReference Include="Annium.linq2db.Extensions" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Abstractions" Version="0.1.0" />
        <PackageReference Include="Annium.Logging.Console" Version="0.1.0" />
        <PackageReference Include="linq2db" Version="2.9.8" />
        <PackageReference Include="Scriban" Version="2.1.1" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
</Project>