<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>XRest.Clients.Csharp</PackageId>
        <PackageVersion>0.1.0</PackageVersion>
        <Description>XRest client for .NET Core</Description>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <LangVersion>11.0</LangVersion>
        <WarningsAsErrors>true</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../sources/XRest.Sources/XRest.Sources.csproj" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates/**" />
        <EmbeddedResource Remove="Templates/.*" />
    </ItemGroup>
</Project>