<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Solutions>Tools</Solutions>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Xdb.Core/Xdb.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dbup-postgresql" />
  </ItemGroup>
</Project>
